/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 untitled.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.5, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials['Material.001']} scale={14} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.gltf')
